### ISSUE TITLE
Question:  how to get authenticated 

### ISSUE THREAD

**Issue by akihikokuroda** [i-am-bee/bee-api#42]
I'm trying to put the bee-stack in kubernetes. https://github.com/i-am-bee/bee-stack/pull/14  I have an issue accessing to the bee-api from the bee-ui.  Is there way to turn off the authentication for debugging purpose?  Do I have to update the JWT token?

Thanks!

**Comment by xjacka** [comment]
Authentication can not be turned off. There is a seeder that creates a user and API key (https://github.com/i-am-bee/bee-api/blob/main/seeders/DatabaseSeeder.ts#L41). To access API you can use either the JWT token: https://github.com/i-am-bee/bee-api/blob/main/src/ui/jwt.key or API key: `sk-proj-testkey`. Simply use an `Authentication` header with the value `Bearer sk-proj-testkey`

**Comment by pilartomas** [comment]
@akihikokuroda The issue is that your MongoDB database isn't running as replicaset which is required by the ORM. It is suggested to use Bee Stack to bootstrap infrastructure. https://github.com/i-am-bee/bee-stack?tab=readme-ov-file#advanced-

**Comment by akihikokuroda** [comment]
@pilartomas Thanks!  It solved the issue.
