### ISSUE TITLE
AUTH_WELL_KNOWN issue ECONNREFUSED

### ISSUE THREAD

**Issue by hebusch** [i-am-bee/bee-api#69]
Hi there! I'm trying to run bee-api in development mode to test some local changes. I’ve started the bee-stack with all containers running except for `bee-api` and `bee-ui`.

However, when I attempt to run bee-api in dev mode, I encounter the following error:

![image](https://github.com/user-attachments/assets/83039e83-9d46-44d4-a669-5e9f1c517434)

I’m a bit puzzled about the service that seems to be expected on port 4001. Is there an additional configuration I need to set up for this?

I’d really appreciate any guidance on this. Thanks in advance!

**Comment by xjacka** [comment]
Can we close? @hebusch
